title: My 2D Java Survival Game Devlog
author: Via
email: avagracejames.2005@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my first devlog (even my 1st survival game!)... so try to be patient with me while I work stuff out.
 I know I'm not gonna be able to post every day, but MAYBE I'll be able to post once or twice a week.
 (I do have school, after all...)

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  agirlcodes99

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
